---
title: "ViraPhD"
author: "Titouan"
date: "2023-02-13"
output: word_document
---

# %C, %N, C stocks and N stocks Analysis

# Bos Khnor 2022

```{r, echo = FALSE,message = FALSE, warning = FALSE}
##1. Pre-requisites
# Packages
library(tidyverse)
library(ggpubr)
library(rstatix)
library(emmeans)
library(multcomp)
library(multcompView)
library(lmerTest)
library(rmarkdown)

# Importing data
setwd(dir = "C:/Users/titou/OneDrive/Bureau/Cambodge 2021/II.Tâches annexes/3.Statistiques & appuiT/statscambodia2023/Thèse Vira & Writing session 2023")
TAB <- read.table("230205_Soil data arrangement for R 2011 vs 2021.csv", header = T,sep = ";", dec = ".", stringsAsFactors = T)

##2. Data preparation
#Reordering Depth factor values
TAB$Depth <- factor(TAB$Depth, levels=c('0-5','5-10','10-20','20-40','40-60','60-80','80-100'))
colnames(TAB)[7:8] <- c("Ncont","Ccont")
TAB$Year <- as.factor(TAB$Year)
TAB$NSTOCK <- as.numeric(TAB$NSTOCK)
TAB$NSTOCK2 <- as.numeric(TAB$NSTOCK2)
```

```{r, message = FALSE, warning = FALSE}
#Checking for aberrant value through statistics
#-> We need to remove negative %N and C/N data
TAB2 <- subset(TAB, Ncont > 0)
#-> We remove N value < 0.3 (Too low) and N value == 2.86 (unexplained high value)
TAB3 <- subset(TAB2, Ncont > 0.3)
TAB4 <- subset(TAB3, Ncont != 2.86)
#-> Some C values are low, we remove all values < 0.03
TAB5 <- subset(TAB4, Ccont > 0.03)
#We remove values of Referent Vegetaion, we will be able to analyze these values later
TAB6 <- subset(TAB5, Experiment != "Referentvegetation")
```

```{r, echo = FALSE,message = FALSE, warning = FALSE}
#T1 - Summary of the data
print("Summary")
summary(TAB)
# () Variables loop
Expe <- TAB6[!duplicated(TAB5$Experiment),1]
Expe <- Expe[2:4]
Dept <- TAB6[!duplicated(TAB5$Depth),3]
Yea <- TAB6[!duplicated(TAB5$Yea),5]
TukRes <- list()
for (i in c(7,8,10,13,14)){
  #T1 - Title of Variable
  print(paste(colnames(TAB6[i])))
  ##3. Descriptive statistics
  #Histogramm
  hist <- ggplot(TAB2, aes(x=TAB2[,i])) + 
  geom_histogram(binwidth=mean(TAB2[,i])/10)+xlab(colnames(TAB2[i]))
  print(hist)
  #Mean & standard deviation
  # () Experiment loop
  for (j in 1:3){
    #T2 - Title of Experiment
    print(paste(colnames(TAB6[i]),Expe[j]))
    #Table preparation
    TAB7 <- subset(TAB6, Experiment == Expe[j])
    DescStats <- TAB7 %>%
    group_by(Year,Depth,Treatment) %>%
    get_summary_stats(colnames(TAB7[i]), type = "mean_sd")
    knitr::kable(DescStats)
    # () Soil depth loop
      for (k in 1:7){
      #T3 - Title of Soil Depth
      print(paste(colnames(TAB7[i]),Expe[j],Dept[k]))
      #Table preparation
      TAB8 <- subset(TAB7, Depth == Dept[k])
      #Boxplots
      bxp <- ggboxplot(TAB8, x = "Year", y = colnames(TAB[i]),
                       color = "Treatment", palette = "jco")+ ggtitle(paste(colnames(TAB[i]),Expe[j],Dept[k]))
      print(bxp)
      ##4. hypothesis checking + ANOVA for each soil depth individually
      #Normality hypothesis
      #Modeling
      model=lmer(TAB8[,i] ~ Treatment*Year+(1|Treatment:Replicate),data=TAB8)
      summary(model)
      #T4 - Normality
      print("Normality")
      #Normality plot
      plot <- ggqqplot(residuals(model))+ ggtitle(paste("Normality",colnames(TAB8[i]),Expe[j],Dept[k]))
      print(plot)
      print("Shapiro test for normality")
      print(shapiro_test(residuals(model)))
      #T4 - Homoscedasticity 
      print("Homoscedasticity")
      #Homoscedasticity plot
      plot2 <- plot(model, main = paste("Normality",colnames(TAB8[i]),Expe[j],Dept[k]))
      print(plot2)
      #Homoscedasticity test
      print("Levene test for homoscedasticity")
      print(TAB8 %>% levene_test(TAB8[,i] ~ Treatment*Year))
      #T4 - ANOVA and CLD
      print("ANOVA")
      #ANOVA, fisher test results
      anova(model)
      #emmeans + Tukey - Synchronic
      moyYeaByTreat =emmeans(model, ~Year|Treatment)
      tukYeaByTreat=cld(moyYeaByTreat)
      print(tukYeaByTreat)
      #emmeans + Tukey - Diachronic
      moyTreatByYea =emmeans(model, ~Treatment|Year)
      tukTreatByYea=cld(moyTreatByYea)
      print(tukTreatByYea)
      tukTreatByYea$Depth <- Dept[k]
      TukRes[[k]] <- tukTreatByYea
      #T4 - ANOVA plot
      print("ANOVA plot")
      #Diachronic plot with confidence interval
      plot <- ggplot(tukYeaByTreat, aes_string(x="Year", y="emmean", colour="Treatment", group="Treatment")) +
        geom_line(aes_string(linetype="Treatment"), size=.6) +
        geom_point(aes_string(shape="Treatment"), size=3) +
        geom_errorbar(aes_string(ymax="upper.CL", ymin="lower.CL"), width=.1) +
        ggtitle(paste(colnames(TAB8[i]),Expe[j],Dept[k]))+
        geom_text(label= tukYeaByTreat$.group, nudge_x=0.1, nudge_y=0.1, check_overlap=F)
      print(plot)
      }
    # "If" loop for % plots depending on soil depth
    if (i < 13){
      #Table preparation with average values
      TAB6$ID <- paste(TAB6$Experiment,TAB6$Treatment,TAB6$Depth,TAB6$Year)
      TAB7b <- as.data.frame(apply(TAB6[,7:14],2,tapply, TAB6$ID, mean))
      ID <- TAB6[,c(1:3,5,16)]
      ID <- ID %>% distinct(ID, .keep_all = TRUE)
      TAB7b$ID <- rownames(TAB7b)
      TAB8b <- merge(ID, TAB7b, by ="ID")
      #Inverser x et y, pb boucle
      TAB9b <- subset(TAB8b, Experiment == Expe[j])
      #Including values of cld in the table
      TukLetter <- rbind(TukRes[[1]],TukRes[[2]],TukRes[[3]],TukRes[[4]],
                         TukRes[[5]],TukRes[[6]],TukRes[[7]])
      TukLetter$IDb <- paste(TukLetter$Treatment,TukLetter$Year,TukLetter$Depth)
      TukLetter <- TukLetter[,c(8,10)]
      TAB9b$IDb <- paste(TAB9b$Treatment, TAB9b$Year, TAB9b$Depth)
      TAB9b <-  merge(TukLetter, TAB9b, by ="IDb")
      #We reverse depth factor values order
      TAB9b$Depth <- factor(TAB9b$Depth, levels=c('80-100','60-80','40-60','20-40','10-20','5-10','0-5'))
      #T3 - Summary for all Soil depths
      print("Summary for soil depths")
      #Plotting the soil content depending on soil depth + significant differences
      plot <- ggplot(TAB9b, aes(x = TAB9b[,i+1], y = Depth, group = Treatment,color = Treatment)) +
        geom_line(aes(color=Treatment))+ geom_point(aes(color=Treatment)) + facet_grid(cols =vars(Year))+
        ggtitle(colnames(TAB9b[i+1]),Expe[j]) + xlab(colnames(TAB9b[i+1]))+
        geom_text(label= TAB9b$.group, nudge_x=0.45, nudge_y=0.1, check_overlap=F)
      print(plot)
    } else {
      ###6. Creation of cumulated stock for soil depths
      TAB7$ID <- paste(TAB7$Experiment,TAB7$Treatment,TAB7$Replicate,TAB7$Year)
      ID <- TAB7[,c(1:2,4:5,16)]
      ID <- ID %>% distinct(ID, .keep_all = TRUE)
      # Data prep For Cumulated layer 0-10, 0-20,0-40, 0-60,0-80, 0-100
      TAB010 <- subset(TAB7, Depth == "0-5" | Depth == "5-10")
      TAB010Cum <- as.data.frame(apply(TAB010[i],2,tapply, TAB010$ID, sum))
      TAB010Cum$ID <- rownames(TAB010Cum)
      TABCumDept <- merge(ID, TAB010Cum, by ="ID")
      colnames(TABCumDept)[6] <- paste(colnames(TAB6)[i],"010")
      #0-20
      TAB020 <- subset(TAB7, Depth == "0-5" | Depth == "5-10" | Depth == "10-20")
      TAB020Cum <- as.data.frame(apply(TAB020[i],2,tapply, TAB020$ID, sum))
      TAB020Cum$ID <- rownames(TAB020Cum)
      TABCumDept2 <- merge(TABCumDept, TAB020Cum, by ="ID")
      colnames(TABCumDept2)[7] <- paste(colnames(TAB6)[i],"020")
      #0-40
      TAB040 <- subset(TAB7, Depth == "0-5" | Depth == "5-10" | Depth == "10-20" | Depth == "20-40")
      TAB040Cum <- as.data.frame(apply(TAB040[i],2,tapply, TAB040$ID, sum))
      TAB040Cum$ID <- rownames(TAB040Cum)
      TABCumDept3 <- merge(TABCumDept2, TAB040Cum, by ="ID")
      colnames(TABCumDept3)[8] <- paste(colnames(TAB6)[i],"040")
      #0-60
      TAB060 <- subset(TAB7, Depth == "0-5" | Depth == "5-10" | Depth == "10-20" | Depth == "20-40" | Depth == "40-60")
      TAB060Cum <- as.data.frame(apply(TAB060[i],2,tapply, TAB060$ID, sum))
      TAB060Cum$ID <- rownames(TAB060Cum)
      TABCumDept4 <- merge(TABCumDept3, TAB060Cum, by ="ID")
      colnames(TABCumDept4)[9] <- paste(colnames(TAB6)[i],"060")
      #0-80
      TAB080 <- subset(TAB7, Depth != "80-100")
      TAB080Cum <- as.data.frame(apply(TAB080[i],2,tapply, TAB080$ID, sum))
      TAB080Cum$ID <- rownames(TAB080Cum)
      TABCumDept5 <- merge(TABCumDept4, TAB080Cum, by ="ID")
      colnames(TABCumDept5)[10] <- paste(colnames(TAB6)[i],"080")
      #0-100
      TAB0100 <- TAB7
      TAB0100Cum <- as.data.frame(apply(TAB0100[i],2,tapply, TAB0100$ID, sum))
      TAB0100Cum$ID <- rownames(TAB0100Cum)
      colnames(TAB0100Cum)[1] <- paste(colnames(TAB6)[i],"0100")
      TABCumDept6 <- merge(TABCumDept5, TAB0100Cum, by ="ID")
      ###7. Modeling for cumulated soil depths
      for (m in 1:6){
          #T3 - Cumulated soil depth
          print(paste(colnames(TABCumDept6[5+m]),"Cumulated",Expe[j]))
          #Model creation
          model=lmer(TABCumDept6[,5+m] ~ Treatment*Year+(1|Treatment:Replicate),data=TABCumDept6)
          #T4 - Normality
          print("Normality")
          #Normality plot
          plot <- ggqqplot(residuals(model))+ ggtitle(paste("Normality",colnames(TABCumDept6[5+m]),Expe[j],Dept[k]))
          print(plot)
          print("Shapiro test for normality")
          print(shapiro_test(residuals(model)))
          #T4 - Homoscedasticity
          print("Homoscedasticity")
          #Homoscedasticity plot
          plot2 <- plot(model, main = paste("Normality",colnames(TABCumDept6[5+m]),Expe[j],Dept[k]))
          print(plot2)
          #Homoscedasticity test
          print("Levene test for homoscedasticity")
          n <- 5+m
          print(TABCumDept6 %>% levene_test(TABCumDept6[,n] ~ Treatment*Year))
          #T4 - ANOVA and CLD
          print("ANOVA")
          #ANOVA, fisher test results
          anova(model)
          #emmeans + Tukey - Synchronic
          moyYeaByTreat =emmeans(model, ~Year|Treatment)
          tukYeaByTreat=cld(moyYeaByTreat)
          print(tukYeaByTreat)
          #emmeans + Tukey - Diachronic
          moyTreatByYea =emmeans(model, ~Treatment|Year)
          tukTreatByYea=cld(moyTreatByYea)
          print(tukTreatByYea)
          #Diachronic plot with confidence interval
          #T4 - ANOVA Plot
          print("ANOVA Plot")
          plot <- ggplot(tukYeaByTreat, aes_string(x="Year", y="emmean", colour="Treatment", group="Treatment")) +
            geom_line(aes_string(linetype="Treatment"), size=.6) +
            geom_point(aes_string(shape="Treatment"), size=3) +
            geom_errorbar(aes_string(ymax="upper.CL", ymin="lower.CL"), width=.1) +
            ggtitle(paste(colnames(TABCumDept6[5+m]),Expe[j]))+
            geom_text(label= tukYeaByTreat$.group, nudge_x=0.1, nudge_y=0.1, check_overlap=F)
          print(plot)
      }
    }
  }
}
```
